#pragma once

#define MASTER_RIGHT

#define TAPPING_TERM 150

#define RGB_MATRIX_TIMEOUT 300000
#define RGB_MATRIX_DEFAULT_HUE 232
#define RGB_MATRIX_DEFAULT_SAT 255
#define RGB_MATRIX_DEFAULT_VAL 240
#define RGB_MATRIX_DEFAULT_ON true
